services:
  backend1:
    build: ./backend
    container_name: backend1
    hostname: backend1
    expose:
      - "5000"
    restart: always

  backend2:
    build: ./backend
    container_name: backend2
    hostname: backend2
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/todo-app/dist:/usr/share/nginx/html/dist
    depends_on:
      - backend1
      - backend2
    restart: always
